/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import poneytoponey.App;

class AppTest {
    @Test
    void appHasRmiPort() {
        assertEquals(7000, App.PORT);
    }
}
