/*
* This source file was generated by the Gradle 'init' task
*/
package poneytoponey;

import java.rmi.registry.*;

public class App {
    public static final int PORT = 7000;

    public static void main(String[] args) {
        ShellView view = new ShellView();
        view.start();
    }
}
