services:
  directory:
    image: poneytoponey-demo
    build: .
    working_dir: /project
    entrypoint: just directory
    volumes:
      - ".:/project"

  client1:
    image: poneytoponey-demo
    build: .
    working_dir: /project
    volumes:
      - ".:/project"
  client2:
    image: poneytoponey-demo
    build: .
    working_dir: /project
    volumes:
      - ".:/project"
