# Start a RMI registry with the CLASSPATH variable defined
# to the folder where we have .class files.
# Otherwise, we'll get java.lang.ClassNotFoundException: poneytoponey.Identity (no security manager: RMI class loader disabled)
rmi:
    echo Starting Java RMI server, just hit Ctrl+c here to stop it.
    CLASSPATH=app/bin/main/ rmiregistry 7000

build:
    javac -d app/src/main/java/poneytoponey/build app/src/main/java/poneytoponey/*.java

client ip:
    echo Starting another client !
    just build
    clear
    java -classpath app/src/main/java/poneytoponey/build poneytoponey.App {{ip}}

directory:
    echo Starting the directory server !
    just build
    clear
    java -classpath app/src/main/java/directory/build directory.DirectoryServer
