# Start a RMI registry with the CLASSPATH variable defined
# to the folder where we have .class files.
# Otherwise, we'll get java.lang.ClassNotFoundException: poneytoponey.Identity (no security manager: RMI class loader disabled)
#
# NOTE: not useful anymore as embedded in clients !
# rmi:
#     echo Starting Java RMI server, just hit Ctrl+c here to stop it.
#     CLASSPATH=app/bin/main/ rmiregistry 7000

build:
    javac -d app/src/main/java/build app/src/main/java/*/*.java

client ip:
    echo Starting another client !
    just build
    java -classpath app/src/main/java/build poneytoponey.App http://{{ip}}:8080

directory:
    echo Starting the directory server !
    just build
    java -classpath app/src/main/java/build directory.DirectoryServer

