@startuml brainstorm

title "Brainstorm poneytoponey design"

hide empty members

interface Chat extends Remote {
    sendMessage(text: String, sender_timestamp: Timestamp)
    close()
}

class DirectChat implements Chat {
    close()
}

interface Identity extends Remote {
    askForChat(ourChat: Identity)
    approveChat(approvedManager: Identity): Chat
}

class HumanIdentity implements Identity {
    username: String
    listParticipantsUsername(): String[]
}

HumanIdentity "1"-"*" DirectChat: manage >
DirectChat "1"-"*" Message: contain >

class Message {
    text: String
    sender_timestamp: Timestamp
    index: Integer
    author: String
}

object Registry

Registry "0..1"-"*" Remote: take notes by String of published >

@enduml