@startuml class

title "Diagramme de classe poneytoponey"

hide empty members

interface Remote <<java.rmi>>

class App
HumanIdentity "1"--"0..1" App: create <
App "1"--"1" View: start >

interface View {
    start(humanIdentity: HumanIdentity)
}

class ShellView implements View {
    - currentChat: Uuid
    - joinedNetwork: bool
    - join(username: String)
    - showHelp()
    - createSwitchChat(recipient: String)
    - closeChat(recipient: String)
    - sendMessage(text: String)
    - listParticipants()
    - askForInput()
    - parseCommand()
}

class Chat {
    -uuid: Uuid
    -approved: bool
    +getUuid(): Uuid
    +getApproved(): bool
}

interface Identity extends Remote {
    +askForChat(ourChat: Identity, chatId: Uuid)
    +approveChat(approvedManager: Identity)
    +sendMessageInChat(chatId: Uuid, text: String, senderTimestamp: Timestamp)
    +closeChat(chatId: Uuid)
}

class HumanIdentity implements Identity {
    -username: String
    +getUsername(): String
    +listParticipantsUsername(): String[]
    +getChats(): Chat[]
    +createChat(): Chat
}

HumanIdentity "1"-"*" Chat: manage >
Chat "1"--"*" Message: contain >

class Message {
    -text: String
    -senderTimestamp: Timestamp
    -index: Integer
    -author: String
}

object Registry

Registry "0..1"-"*" Remote: take notes by String of published >

@enduml