@startuml requirements
title Requirements diagram
skinparam rectangle<<Requirement>> {
  BackgroundColor LightBlue
  BorderColor Blue
}

rectangle "Chatter dans le réseau" <<Requirement>> as r1
rectangle "Gérer des chats directs" <<Requirement>> as r2
rectangle "Envoyer des messages dans des chats" <<Requirement>> as r3
rectangle "Découvrir les autres membres du réseau" <<Requirement>> as r4

rectangle "Central registry" <<block>> as registry

r1 <.. r2 : refine
r1 <.. r3 : refine
r1 <.. r4 : refine

r1 <. registry : satisfy

@enduml
